### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by JoaoCnh** [krakenjs/kraken-example-with-passport#14]
Hey I just started trying Kraken out and I'm seeing this repo to config passport into Kraken.

I've pretty much figured it out but now isAuthenticated is called when I go to root route ('/') and even on /login, which it shouldn't.

Is there something I'm missing? Where can I find the file where we control this?

**Comment by grawk** [comment]
`isAuthenticated` is added to the middleware chain here:
https://github.com/krakenjs/kraken-example-with-passport/blob/master/config/config.json#L89-L96
