### ISSUE TITLE
failed bcrypt install + quickfix

### ISSUE THREAD

**Issue by xShirase** [krakenjs/kraken-example-with-passport#8]
Environment : 
 `Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)`
`node  v0.12.2`
`npm  v2.7.4`
`node-gyp  v1.0.3`

`npm i`  fails on installing bcrypt

Here's the error : 
`gyp ERR! build error`
`gyp ERR! stack Error: `make` failed with exit code: 2`
`gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)`
`gyp ERR! stack     at ChildProcess.emit (events.js:110:17)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)`
`gyp ERR! System Linux 3.13.0-48-generic`
`gyp ERR! command "node" "/home/ubuntu/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"`
`gyp ERR! cwd /home/ubuntu/kraken-examples/with.passport/node_modules/bcrypt`
`gyp ERR! node -v v0.12.2`
`gyp ERR! node-gyp -v v1.0.3`
`gyp ERR! not ok`
`npm ERR! Linux 3.13.0-48-generic`
`npm ERR! argv "/home/ubuntu/.nvm/versions/node/v0.12.2/bin/node" "/home/ubuntu/.nvm/versions/node/v0.12.2/bin/npm" "i" "bcrypt"`
`npm ERR! node v0.12.2`
`npm ERR! npm  v2.7.4`
`npm ERR! code ELIFECYCLE`

**Instead of going through the hassle of debugging node-gyp issues, an easy fix is to change the version in package.json to "^0.8.1", which is probably better anyway.**

**Comment by xShirase** [comment]
After looking further, it appears that the package.json on this repo is correct, but not the one on 
`git@github.com:krakenjs/kraken-examples.git`, which is the repo linked to in the README. 
I'll fw the issue, but maybe the README should point us to this repo instead of the other one?

**Comment by aredridel** [comment]
Which readme?

**Comment by xShirase** [comment]
https://github.com/krakenjs/kraken-example-with-passport/blob/master/README.md

**Comment by xShirase** [comment]
there's already a pull request fixing this and the bcrypt version in this repo. Having 2repos cross-referencing is kinda confusing ;)

to sum up : 
On this repo : bcrypt version is fine, but the readme sends us to clone the merged repo with all the examples

On the merged repo : bcrypt version is 0.7.7, which causes errors. See https://github.com/krakenjs/kraken-examples/pull/45

**Comment by aredridel** [comment]
Indeed. I'm going to work on killing off the combined repo today.

**Comment by aredridel** [comment]
Closing this issue since with merging #6 fixes the instructions.
